import requests

url = "http://127.0.0.1:5500/api/propiedades"

propiedades = [
    {
        "nombre": "Casa Jardines del Valle",
        "precio": 3500000,
        "renta": None,
        "tipo": "casa",
        "habitaciones": 3,
        "banos": 2,
        "area": 180,
        "estacionamientos": 2,
        "descripcion": "Casa remodelada con jardín y cocina integral.",
        "categoria": "venta",
        "userid": "Rk9ALLS90CQ5fRFvP72JWxiphJ82",
        "antiguedad": 10,
        "financiamiento": True,
        "servicios": ["internet", "seguridad"],
        "remodelar": False,
        "precionegociable": True,
        "isinvestment": False,
        "paybackyears": "0",
        "roi": None,
        "imagen": "https://ejemplo.com/img1.jpg",
        "status": "publicada",
        "fecha": "2025-06-06T10:00:00",
        "visitas": {"fecha": "2025-06-01T09:00:00", "cantidad": 5}
    },
    {
        "nombre": "Depa en Ladrón de Guevara",
        "precio": 4200000,
        "renta": 18000,
        "tipo": "departamento",
        "habitaciones": 2,
        "banos": 2,
        "area": 120,
        "estacionamientos": 1,
        "descripcion": "Departamento con excelente ubicación y vista.",
        "categoria": "venta",
        "userid": "Rk9ALLS90CQ5fRFvP72JWxiphJ82",
        "antiguedad": 4,
        "financiamiento": False,
        "servicios": ["internet", "seguridad", "piscina"],
        "remodelar": False,
        "precionegociable": False,
        "isinvestment": True,
        "paybackyears": "14",
        "roi": 6.8,
        "imagen": "https://ejemplo.com/img2.jpg",
        "status": "nuevo",
        "fecha": "2025-06-06T11:00:00",
        "visitas": {"fecha": "2025-06-03T10:00:00", "cantidad": 3}
    },
    {
        "nombre": "Casa en Tlajomulco",
        "precio": 1800000,
        "renta": None,
        "tipo": "casa",
        "habitaciones": 2,
        "banos": 1,
        "area": 100,
        "estacionamientos": 1,
        "descripcion": "Ideal para familias pequeñas, buena plusvalía.",
        "categoria": "venta",
        "userid": "Rk9ALLS90CQ5fRFvP72JWxiphJ82",
        "antiguedad": 8,
        "financiamiento": True,
        "servicios": ["internet"],
        "remodelar": True,
        "precionegociable": True,
        "isinvestment": True,
        "paybackyears": "10",
        "roi": 10.2,
        "imagen": "https://ejemplo.com/img3.jpg",
        "status": "publicada",
        "fecha": "2025-06-06T12:00:00",
        "visitas": {"fecha": "2025-06-02T13:00:00", "cantidad": 7}
    },
    {
        "nombre": "Oficina en Providencia",
        "precio": 8800000,
        "renta": 42000,
        "tipo": "oficina",
        "habitaciones": 5,
        "banos": 3,
        "area": 300,
        "estacionamientos": 4,
        "descripcion": "Oficina con divisiones listas, recepción y sala de juntas.",
        "categoria": "venta",
        "userid": "Rk9ALLS90CQ5fRFvP72JWxiphJ82",
        "antiguedad": 12,
        "financiamiento": False,
        "servicios": ["seguridad", "internet"],
        "remodelar": False,
        "precionegociable": False,
        "isinvestment": True,
        "paybackyears": "9",
        "roi": 5.3,
        "imagen": "https://ejemplo.com/img4.jpg",
        "status": "publicada",
        "fecha": "2025-06-06T13:00:00",
        "visitas": {"fecha": "2025-06-01T09:00:00", "cantidad": 10}
    },
    {
        "nombre": "Terreno en Chapala",
        "precio": 1200000,
        "renta": None,
        "tipo": "terreno",
        "habitaciones": 0,
        "banos": 0,
        "area": 600,
        "estacionamientos": 0,
        "descripcion": "Terreno con vista al lago, listo para construir.",
        "categoria": "venta",
        "userid": "Rk9ALLS90CQ5fRFvP72JWxiphJ82",
        "antiguedad": 0,
        "financiamiento": True,
        "servicios": [],
        "remodelar": False,
        "precionegociable": True,
        "isinvestment": True,
        "paybackyears": "6",
        "roi": 9.1,
        "imagen": "https://ejemplo.com/img5.jpg",
        "status": "nuevo",
        "fecha": "2025-06-06T14:00:00",
        "visitas": {"fecha": "2025-06-04T15:00:00", "cantidad": 2}
    }
]

for propiedad in propiedades:
    res = requests.post(url, json=propiedad)
    print(f"Status: {res.status_code} | Respuesta: {res.json()}")